---
  plugins:
    - html
  settings:
    html/html-extensions:
      - .html
      - .vue
  globals:
    $: true
    jQuery: true
  env:
    browser: true
    node: true
  extends: idiomatic
  parser: babel-eslint
  parserOptions:
    ecmaVersion: 8
    sourceType: module
  rules:
    one-var: 0
    quotes:
      - 1
      - backtick
    no-unused-vars: 0
    no-debugger: 0
    no-console: 0
    no-inline-comments: 0
    vars-on-top: 0
    prefer-template: 1
    semi: 1
    comma-dangle:
      - 1
      - arrays: always-multiline
        objects: always-multiline